//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globals.SettingFiles {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    public sealed partial class PassKey : global::System.Configuration.ApplicationSettingsBase {
        
        private static PassKey defaultInstance = ((PassKey)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PassKey())));
        
        public static PassKey Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyPassKey {
            get {
                return ((string)(this["MyPassKey"]));
            }
            set {
                this["MyPassKey"] = value;
            }
        }
    }
}
