//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubControlSupplierProject.ViewModel.NewSchemaUserControl.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubControlSupplierProject.ViewModel.NewSchemaUserControl.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole wyboru.
        /// </summary>
        internal static string checkBox {
            get {
                return ResourceManager.GetString("checkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista rozwijalna.
        /// </summary>
        internal static string comboBox {
            get {
                return ResourceManager.GetString("comboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa elementu.
        /// </summary>
        internal static string itemName {
            get {
                return ResourceManager.GetString("itemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ elementu.
        /// </summary>
        internal static string itemType {
            get {
                return ResourceManager.GetString("itemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nawa schematu.
        /// </summary>
        internal static string schemaName {
            get {
                return ResourceManager.GetString("schemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole tekstowe.
        /// </summary>
        internal static string textBox {
            get {
                return ResourceManager.GetString("textBox", resourceCulture);
            }
        }
    }
}
